import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-base-100">
          <div className="navbar-start">
            <a className="btn btn-ghost btn-circle" href="/">
              <img src="/favicon.ico" alt="Sam Kaveh" />
            </a>
          </div>
          <div className="navbar-center">
            <div className="btn-group">
              <a className="btn btn-neutral btn-sm" href="/">
                About Me
              </a>
              <a className="btn btn-neutral btn-sm" href="/projects/">
                Projects
              </a>
            </div>
          </div>
          <div className="navbar-end"></div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
